FROM ubuntu:16.04
MAINTAINER Ling-Hong Hung
#To use:
#cd <kallisto repo>
#then either run ./buildAll.sh or the individual commands
#sudo docker build -t kallisto-build -f Dockerfile-build .
#sudo docker run --rm -it -v ${PWD}:/data  kallisto build

RUN apt-get update && apt-get install -y build-essential cmake autoconf automake git \
 zlib1g-dev libhdf5-dev libbz2-dev liblzma-dev
RUN git clone https://github.com/samtools/htslib
RUN cd htslib && autoreconf -i && ./configure && make
RUN git clone https://github.com/pachterlab/kallisto.git
RUN cd kallisto && mkdir -p ./build && rm -r ext/htslib && cp -r ../htslib ext && cd build && cmake .. && make && make install


