# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InventoryItem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str = None, host: str = None):  # noqa: E501
        """InventoryItem - a model defined in Swagger

        :param id: The id of this InventoryItem.  # noqa: E501
        :type id: str
        :param host: The host of this InventoryItem.  # noqa: E501
        :type host: str
        """
        self.swagger_types = {"id": str, "host": str}

        self.attribute_map = {"id": "id", "host": "host"}

        self._id = id
        self._host = host

    @classmethod
    def from_dict(cls, dikt) -> "InventoryItem":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InventoryItem of this InventoryItem.  # noqa: E501
        :rtype: InventoryItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this InventoryItem.


        :return: The id of this InventoryItem.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this InventoryItem.


        :param id: The id of this InventoryItem.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def host(self) -> str:
        """Gets the host of this InventoryItem.


        :return: The host of this InventoryItem.
        :rtype: str
        """
        return self._host

    @host.setter
    def host(self, host: str):
        """Sets the host of this InventoryItem.


        :param host: The host of this InventoryItem.
        :type host: str
        """
        if host is None:
            raise ValueError(
                "Invalid value for `host`, must not be `None`"
            )  # noqa: E501

        self._host = host
