// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "01639a27-f51c-46ea-a30f-ff482d28d6cb");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1676344543);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1676344570);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{5411ab48-9a04-4178-9fc5-7d2fb695553b}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1676344540);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 133);
user_pref("browser.newtabpage.activity-stream.impressionId", "{3cf5f8f3-93e1-4e15-a33f-f1f10b35e26c}");
user_pref("browser.newtabpage.enabled", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1676344541);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1676344543271");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1676366143271");
user_pref("browser.search.region", "US");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20221221095321");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage", "chrome://browser/content/blanktab.html");
user_pref("browser.startup.homepage_override.buildID", "20221221095321");
user_pref("browser.startup.homepage_override.mstone", "108.0.1");
user_pref("browser.startup.homepage_override.once", "{\"message_id\":\"WNP_MOMENTS_14\",\"url\":\"https://www.mozilla.org/firefox/welcome/14\",\"expire\":1668470400000}");
user_pref("browser.startup.lastColdStartupCheck", 1676344570);
user_pref("browser.toolbars.bookmarks.visibility", "always");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":18,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "offline");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1676344541689");
user_pref("distribution.fedora.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "108.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "US");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "74c86f6f49e94e768a23b774e64b5b20");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20221221095321");
user_pref("extensions.lastAppVersion", "108.0.1");
user_pref("extensions.lastPlatformVersion", "108.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"c4cfe970-ea80-4c9c-89b1-0305bfaa42ba\",\"pictureinpicture@mozilla.org\":\"55c36aff-12af-4eec-99ee-e427e3e9530c\",\"screenshots@mozilla.org\":\"40fb1535-2e15-42c8-a791-1eb86726a6fb\",\"webcompat-reporter@mozilla.org\":\"323d4bc9-f23e-4e2d-a3f9-d7d34ef3db8a\",\"webcompat@mozilla.org\":\"56ae25fa-594a-4220-aac7-8a7897798c73\",\"default-theme@mozilla.org\":\"8785fd89-8687-4fae-a255-004e4ca07991\",\"addons-search-detection@mozilla.com\":\"346e9e35-f6a5-4757-868c-9956b8182582\",\"google@search.mozilla.org\":\"ec2a244f-f1e0-42ae-8c9e-adf815f31703\",\"amazondotcom@search.mozilla.org\":\"b9e3471a-6142-4fa9-a286-7785d188f852\",\"wikipedia@search.mozilla.org\":\"cb5567e2-981c-4498-917a-67c4d8466143\",\"bing@search.mozilla.org\":\"2d6def7e-7785-4b16-8e90-da07b11c7da3\",\"ddg@search.mozilla.org\":\"00b886e9-86f4-45c5-ba4e-0c94ea1a3286\",\"ebay@search.mozilla.org\":\"644c2fd0-44eb-4a3c-b6ba-0ad441190b15\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1676344542);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "e18c86b3-0a7a-4d92-a724-462c79d2a448");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.engine.addresses.available", true);
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("toolkit.startup.last_success", 1676344569);
user_pref("toolkit.telemetry.cachedClientID", "45697bf1-258d-4e82-bd7b-6c8d08a6593f");
user_pref("toolkit.telemetry.previousBuildID", "20221221095321");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
