
cmd_args <- commandArgs(TRUE)
if(length(cmd_args) < 3){
    cat(paste("Usage: Rscript counts2DESeq.R [Counts Table File] [Sample Table File] [Output directory]\n"))
    cat("\n")
    cat("Arguments:\n\n")
    cat("\t[Counts Table File] A counts table generated by bam2counts.R \n\n")
    cat("\t[Sample Table File] is a table with detailed information for each of samples that links samples to the associated FASTQ and BAM files.\n\n")
    cat("\t[Output directory] is the output for saving result table.\n\n")
    stop()
}

start.time <- Sys.time()

counts_file <- cmd_args[1]
sample_table <- cmd_args[2]
output_dir <- cmd_args[3]

print("Loading sample table......")
sampleTable <- read.csv(sample_table, row.names = 1)

print("Loading counts table......")
bam_counts <- read.csv(counts_file)
bam_counts <- as.matrix(bam_counts)

library("DESeq2")
print("DESeq......")

(coldata <- data.frame(row.names=colnames(bam_counts), sampleTable))
dds <- DESeqDataSetFromMatrix(bam_counts, coldata, ~ cell + dex)

dds_file <- file.path(output_dir, "dds.RDATA")
print(paste0("Saving dds to: ", dds_file))
save(dds, file=dds_file)

result_file <- file.path(output_dir, "deseq_results.csv")
print(paste0("Generating and saving result table to: ", result_file))
dds <- DESeq(dds)
res <- results(dds)
resOrdered <- res[order(res$pvalue),]
write.csv(as.data.frame(resOrdered), file=result_file)

end.time <- Sys.time()
time.taken <- end.time - start.time

print(paste0("Time used: ", time.taken))
