name: Push Latest Docker images
on:
  push:
    branches: master
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push standard image to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/bwb:latest
      - name: Push development image to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile-widgets
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/bwb-dev:latest
